
server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shigal/spring-cloud-config-store.git
          search-paths:
            - '*service'
#          username: root
#          passphrase: 1234

